version: 2.1

jobs:
  print-hello:
    docker:
      - image: circleci/node:14.7
    steps:
      - run: echo "hello"
  print-world:
    docker:
      - image: circleci/node:14.7
    steps:
      - run: echo "world"

workflows:
  hello-world:
    jobs:
      - print-hello
      - print-world:
          requires:
            - print-hello
